var location = [
  {
    id: 1,
    title: 'SUNDARBANS',
    origin: '',
    sub_title: 'Text about sajek',
    details:
      'The Sundarbans is a mangrove area in the delta formed by the confluence of the Ganges, Brahmaputra and Meghna Rivers in the Bay of Bengal. It spans from the Hooghly River in Indias state of West Bengal to the Baleswar River in Bangladesh.',
    price: 23.99,
    img: 'sundorbon.png',
    lat: 21.9704426,
    lng: 89.78811589676832,
  },
  {
    id: 2,
    title: 'SAJEK',
    origin: '',
    sub_taitle: 'Text about sajek',
    details:
      'Sajek valley is known for its natural environment and is surrounded by mountains, dense forest, and grassland hill tracks. Many small rivers flow through the mountains among which the Kachalong and the Machalong are notable. On the way to Sajek valley, one has to cross the Mayni range and the Mayni river.',
    price: 25.99,
    img: 'Sajek.png',
    lat: 23.3831187,
    lng: 92.29356427321036,
  },
  {
    id: 3,
    title: 'SREEMONGOL',
    origin: '',
    sub_taitle: 'Text about sreemongol',
    details:
      'Madhobpur Lake is one of the main tourist attractions in the area and is home to the Great White-Bellied Heron, the only confirmed site in Bangladesh.',
    price: 33.99,
    img: 'Sreemongol.png',
    lat: 24.3105781,
    lng: 91.725133,
  },
  {
    id: 4,
    title: 'Hotel 5 STAR',
    origin: 'SUNDARBANS',
    sub_taitle: 'Text about hotel',
    details: 'Simple Description about Hotel 5 STAR',
    price: 233.99,
    img: 'hotel1.png',
    lat: 21.9704426,
    lng: 89.78811589676832,
  },
  {
    id: 5,
    title: 'Hotel MAX M',
    origin: 'SUNDARBANS',
    sub_taitle: 'Text about hotel',
    details: 'Simple Description about Hotel MAX M',
    price: 133.99,
    img: 'hotel2.png',
    lat: 21.9704426,
    lng: 89.78811589676832,
  },
  {
    id: 6,
    title: 'PRIANCE PLACE',
    origin: 'SUNDARBANS',
    sub_taitle: 'Text about hotel',
    details: 'Simple Description about Hotel MAX M',
    price: 163.99,
    img: 'hotel3.png',
    lat: 21.9704426,
    lng: 89.78811589676832,
  },
  {
    id: 7,
    title: 'Hotel 3 STAR',
    origin: 'SAJEK',
    sub_taitle: 'Text about hotel',
    details: 'Simple Description about Hotel 3 STAR',
    price: 133.99,
    img: 'hotel2.png',
    lat: 23.3831187,
    lng: 92.29356427321036,
  },
  {
    id: 8,
    title: 'ORKID',
    origin: 'SAJEK',
    sub_taitle: 'Text about hotel',
    details: 'Simple Description about ORKID',
    price: 193.99,
    img: 'hotel1.png',
    lat: 23.3831187,
    lng: 92.29356427321036,
  },
  {
    id: 9,
    title: 'LOREN NIGHT',
    origin: 'SAJEK',
    sub_taitle: 'Text about hotel',
    details: 'Simple Description about LOREN NIGHT',
    price: 163.99,
    img: 'hotel3.png',
    lat: 23.3831187,
    lng: 92.29356427321036,
  },
  {
    id: 10,
    title: 'GOOD DREAM',
    origin: 'SREEMONGOL',
    sub_taitle: 'Text about hotel',
    details: 'Simple Description about GOOD DREAM',
    price: 169.99,
    img: 'hotel3.png',
    lat: 24.3105781,
    lng: 91.725133,
  },
  {
    id: 11,
    title: 'SKY LINE',
    origin: 'SREEMONGOL',
    sub_taitle: 'Text about hotel',
    details: 'Simple Description about SKY LINE',
    price: 195.99,
    img: 'hotel1.png',
    lat: 24.3105781,
    lng: 91.725133,
  },
  {
    id: 12,
    title: 'SAND NIGHT',
    origin: 'SREEMONGOL',
    sub_taitle: 'Text about hotel',
    details: 'Simple Description about SAND NIGHT',
    price: 160.99,
    img: 'hotel2.png',
    lat: 24.3105781,
    lng: 91.725133,
  },
];

export default location;
